- app/controllers/api/projects_controller.rb
- app/models/project.rb
- app/models/user.rb
- app/views/api/projects/_project.jbuilder
- app/views/api/projects/create.jbuilder
- app/views/api/users/me.jbuilder
- client/src/api/projects.js
- client/src/forms/CreateProject.vue
- client/src/pages/Dashboard.vue
- client/src/store/index.js
- client/src/store/modules/projects.js
- client/src/store/modules/users.js
- client/src/utils.js
- config/routes.rb
- db/migrate/20170109212722_create_projects.rb
- db/schema.rb
- spec/factories/projects.rb
- spec/requests/api/projects_request_spec.rb
- spec/requests/api/users_request_spec.rb
- spec/support/api/schemas/projects/project.json
- spec/support/api/schemas/users/me.json
> Add: #3 list and create projects

- app/controllers/api/projects_controller.rb
- app/models/user.rb
- app/views/api/projects/_project.jbuilder
- app/views/api/projects/find.jbuilder
- app/views/api/projects/update.jbuilder
- client/src/api/http.js
- client/src/api/projects.js
- client/src/components/forms/EditProject.vue
- client/src/components/layout/Project.vue
- client/src/components/pages/Dashboard.vue
- client/src/components/pages/projects/Edit.vue
- client/src/components/pages/projects/Show.vue
- client/src/router.js
- client/src/store/modules/projects.js
- client/src/store/modules/users.js
- config/routes.rb
- db/migrate/20170113231928_add_description_to_project.rb
- db/migrate/20170114113847_add_index_on_project_name.rb
- db/schema.rb
- spec/requests/api/projects_request_spec.rb
- spec/support/api/schemas/projects/project.json
> add: #4 Show and edit projects

- app/controllers/api/welcome_controller.rb
- config/routes.rb
- spec/requests/api/welcome_request_spec.rb
> tec: #28 Add not_found endpoint to API

- client/src/components/Btn.vue
- client/src/components/Container.vue
- client/src/components/EmailField.vue
- client/src/components/FormGroup.vue
- client/src/components/ListItem.vue
- client/src/components/PasswordField.vue
- client/src/components/TextField.vue
- client/src/components/forms/ActivateUser.vue
- client/src/components/forms/CreateProject.vue
- client/src/components/forms/EditProject.vue
- client/src/components/forms/Login.vue
- client/src/components/forms/Register.vue
- client/src/components/layout/App.vue
- client/src/components/layout/AppHeader.vue
- client/src/components/layout/Project.vue
- client/src/components/pages/Dashboard.vue
- client/src/components/pages/Home.vue
- client/src/components/pages/Loading.vue
- client/src/components/pages/projects/Show.vue
- client/src/main.js
> Add: #23 Start design

- app/controllers/api/projects_controller.rb
- app/controllers/api/users_controller.rb
- app/models/project.rb
- app/views/api/projects/_project.jbuilder
- app/views/api/projects/finish.jbuilder
- app/views/api/projects/get_finished.jbuilder
- app/views/api/users/me.jbuilder
- client/src/api/projects.js
- client/src/components/forms/FinishProject.vue
- client/src/components/pages/Dashboard.vue
- client/src/components/pages/projects/Finish.vue
- client/src/components/pages/projects/Show.vue
- client/src/router.js
- client/src/store/modules/projects.js
- client/src/store/modules/users.js
- config/routes.rb
- db/migrate/20170116065712_add_finished_at_to_project.rb
- db/schema.rb
- spec/factories/projects.rb
- spec/models/project_spec.rb
- spec/requests/api/projects_request_spec.rb
- spec/requests/api/users_request_spec.rb
- spec/support/api/schemas/projects/get_finished.json
- spec/support/api/schemas/projects/project.json
- spec/support/api/schemas/users/me.json
> Add: #6 Finish projects

- app/controllers/api/projects_controller.rb
- app/models/project.rb
- app/views/api/projects/_project.jbuilder
- app/views/api/projects/stop.jbuilder
- client/src/api/projects.js
- client/src/components/Btn.vue
- client/src/components/pages/Dashboard.vue
- client/src/components/pages/projects/Show.vue
- client/src/store/modules/projects.js
- config/routes.rb
- db/migrate/20170116212138_add_stopped_at_to_project.rb
- db/schema.rb
- spec/factories/projects.rb
- spec/models/project_spec.rb
- spec/requests/api/projects_request_spec.rb
- spec/support/api/schemas/projects/project.json
> Add: #7 Stop projects

- app/controllers/api/projects_controller.rb
- app/controllers/api/users_controller.rb
- app/controllers/api/welcome_controller.rb
- app/controllers/application_controller.rb
- app/models/project.rb
- app/models/user.rb
- app/views/api/errors/custom_error.jbuilder
- app/views/api/errors/parameter_missing.jbuilder
- app/views/api/errors/record_invalid.jbuilder
- app/views/api/errors/record_not_found.jbuilder
- spec/factories/user.rb
- spec/requests/api/projects_request_spec.rb
- spec/requests/api/users_request_spec.rb
- spec/requests/api/welcome_request_spec.rb
- spec/support/api/schemas/error.json
- spec/support/api/schemas/errors/custom_error.json
- spec/support/api/schemas/errors/parameter_missing.json
- spec/support/api/schemas/errors/record_invalid.json
- spec/support/api/schemas/errors/record_not_found.json
> tec: #22 Improve exceptions handling

- client/package.json
- client/src/components/fields/PasswordField.vue
- client/src/components/forms/ActivateUser.vue
- client/src/components/forms/CreateProject.vue
- client/src/components/forms/EditProject.vue
- client/src/components/forms/FinishProject.vue
- client/src/components/forms/Login.vue
- client/src/components/forms/Register.vue
- client/src/components/forms/StartProject.vue
- client/src/components/layout/AppHeader.vue
- client/src/components/layout/Project.vue
- client/src/components/pages/ActivateUser.vue
- client/src/components/pages/Dashboard.vue
- client/src/components/pages/Error.vue
- client/src/components/pages/Home.vue
- client/src/components/pages/Loading.vue
- client/src/components/pages/Login.vue
- client/src/components/pages/NotFound.vue
- client/src/components/pages/projects/Finish.vue
- client/src/components/pages/projects/Show.vue
- client/src/locales/en.js
- client/src/locales/index.js
- client/src/main.js
> tec: #16 Configure i18n

- app/models/user.rb
- client/src/locales/en.js
- spec/models/user_spec.rb
> tec: #47 Keep a (basic) list of reserved usernames

- spec/requests/api/projects_request_spec.rb
- spec/requests/api/users_request_spec.rb
- spec/requests/api/welcome_request_spec.rb
- spec/shared_examples_for_failures.rb
> tec: #33 Factorize test cases

- CHANGELOG.md
- config/environments/production.rb
- docs/deployment.md
> tec: #56 Support HTTPS in emails

- client/index.html
> tec: #62 Improve responsive design

- app/controllers/api/tasks_controller.rb
- app/models/task.rb
- app/views/api/tasks/backlog.jbuilder
- client/src/api/tasks.js
- client/src/components/forms/CreateTask.vue
- client/src/components/layout/Tasks.vue
- client/src/components/pages/Dashboard.vue
- client/src/components/pages/tasks/Backlog.vue
- client/src/components/pages/tasks/Planning.vue
- client/src/locales/en.js
- client/src/router.js
- client/src/store/modules/tasks.js
- config/routes.rb
- spec/factories/tasks.rb
- spec/requests/api/tasks_request_spec.rb
- spec/support/api/schemas/tasks/backlog.json
> Add: #69 tasks backlog

- app/models/project.rb
- app/models/user.rb
- client/src/components/forms/ActivateUser.vue
- client/src/components/forms/CreateProject.vue
- client/src/components/forms/EditProject.vue
- client/src/locales/en.js
- spec/requests/api/projects_request_spec.rb
- spec/requests/api/users_request_spec.rb
> add: #30 Limit length of projects name and users username

- client/package-lock.json
- client/package.json
- client/src/components/fields/TextField.vue
> add: #61 Autosize textarea according to content

- client/src/components/fields/DateField.vue
- client/src/components/fields/FormGroup.vue
> add: #60 Use date type for date inputs

- app/controllers/api/tasks_controller.rb
- app/models/task.rb
- app/views/api/tasks/_task.jbuilder
- app/views/api/tasks/abandon.jbuilder
- app/views/api/tasks/update.jbuilder
- client/src/api/tasks.js
- client/src/components/Popover/Popover.vue
- client/src/components/Popover/PopoverItem.vue
- client/src/components/Popover/index.js
- client/src/components/forms/EditTask.vue
- client/src/components/tasks/TaskItem.vue
- client/src/locales/en.js
- client/src/main.js
- client/src/store/modules/tasks.js
- config/routes.rb
- db/migrate/20170529210621_add_abandoned_at_to_task.rb
- db/schema.rb
- spec/factories/tasks.rb
- spec/requests/api/tasks_request_spec.rb
- spec/support/api/schemas/tasks/task.json
> add: #66 Add more actions on tasks

- app/models/task.rb
- app/views/api/tasks/_task.jbuilder
- client/package-lock.json
- client/package.json
- client/src/components/Badge.vue
- client/src/components/tasks/TaskItem.vue
- client/src/locales/en.js
- client/src/main.js
- client/src/styles/app.scss
- client/src/styles/components/_vue_directive_tooltip.scss
- db/migrate/20170531195512_add_restarted_count_to_task.rb
- db/schema.rb
- spec/requests/api/tasks_request_spec.rb
- spec/support/api/schemas/tasks/task.json
> add: #68 Add help on repeated tasks

- app/controllers/api/tasks_controller.rb
- app/models/task.rb
- app/views/api/tasks/_task.jbuilder
- app/views/api/tasks/order_after.jbuilder
- client/package-lock.json
- client/package.json
- client/src/api/tasks.js
- client/src/components/pages/Dashboard.vue
- client/src/components/pages/tasks/Backlog.vue
- client/src/components/pages/tasks/Planning.vue
- client/src/components/tasks/TaskItem.vue
- client/src/components/tasks/TaskList.vue
- client/src/store/modules/tasks.js
- config/routes.rb
- db/migrate/20170601094145_add_order_to_task.rb
- db/schema.rb
- spec/factories/tasks.rb
- spec/models/task_spec.rb
- spec/requests/api/tasks_request_spec.rb
- spec/support/api/schemas/tasks/order_after.json
- spec/support/api/schemas/tasks/task.json
> add: #67 Order tasks

- app/views/api/tasks/_task.jbuilder
- client/src/components/tasks/TaskItem.vue
- client/src/locales/en.js
- client/src/store/modules/tasks.js
- spec/support/api/schemas/tasks/task.json
> add: #88 Add a badge about task's creation date

- client/src/components/layout/App.vue
- client/src/styles/app.scss
> tec: #92 Set max-width 100% on img

- client/src/components/layout/App.vue
- client/src/store/modules/tasks.js
- client/src/styles/app.scss
> fix: #91 Hide abandoned tasks on dashboard

- client/src/components/Card.vue
- client/src/components/Container.vue
- client/src/components/ListItem.vue
- client/src/components/layout/AppContent.vue
- client/src/components/layout/AppHeader.vue
- client/src/components/layout/AppSidebar.vue
- client/src/components/pages/Dashboard.vue
- client/src/components/tasks/TaskItem.vue
- client/src/styles/app.scss
- client/src/styles/variables/_dimensions.scss
> tec: #97 Improve design on small devices

- client/src/components/forms/CreateProject.vue
- client/src/components/forms/CreateTask.vue
- client/src/components/forms/EditProject.vue
- client/src/components/forms/EditTask.vue
> tec: #101 Remove autocomplete on task and project

- client/src/components/DateBarIndicator.vue
- client/src/components/pages/Dashboard.vue
- client/src/locales/en.js
- client/src/styles/variables/_colors.scss
> add: #96 Add a project's deadline visualisation

- Gemfile
- Gemfile.lock
- db/seeds.rb
- docs/installation.md
> tec: #106 Provide dev seeds

- client/src/components/tasks/TaskItem.vue
> imp: #114 Hide indicators on finished tasks

- client/src/components/tasks/TaskItem.vue
> imp: #111 Add autofocus on edit task form

- client/package-lock.json
- client/package.json
- client/src/components/BarChart.vue
- client/src/components/LineChart.vue
- client/src/components/layout/AppHeader.vue
- client/src/components/pages/Statistics.vue
- client/src/router.js
- client/src/store/modules/tasks.js
> add: #104 Provide a statistics page

- app/controllers/api/tasks_controller.rb
- client/src/api/tasks.js
- client/src/components/tasks/TaskItem.vue
- client/src/locales/en.js
- client/src/store/modules/tasks.js
- spec/requests/api/tasks_request_spec.rb
> add: #113 Send tasks back to the backlog

- client/src/store/modules/tasks.js
> fix: #121 Don't list finished tassks in backlog

- app/controllers/api/tasks_controller.rb
- app/models/project.rb
- app/models/task.rb
- app/views/api/projects/_project.jbuilder
- app/views/api/tasks/_task.jbuilder
- client/src/api/tasks.js
- client/src/components/forms/CreateTask.vue
- client/src/components/pages/Dashboard.vue
- client/src/components/pages/projects/Show.vue
- client/src/components/tasks/TaskItem.vue
- client/src/components/tasks/TaskList.vue
- client/src/locales/en.js
- client/src/store/modules/projects.js
- client/src/store/modules/tasks.js
- db/migrate/20170716102855_add_project_references_to_task.rb
- db/schema.rb
- spec/requests/api/projects_request_spec.rb
- spec/requests/api/tasks_request_spec.rb
- spec/support/api/schemas/projects/project.json
- spec/support/api/schemas/tasks/task.json
> add: #95 Associate tasks to project

- client/src/components/layout/AppHeader.vue
> fix: #124 Hide statistics button when not logged

- docs/index.md
- docs/release.md
> doc: #90 Document release process

- CHANGELOG.md
> release: #99 Version 0.3

- db/seeds.rb
- delete existing data
- log what's happening
- show credentials to start hacking
> tec: Improve seeds

- config/routes.rb
> tec: #143 Don't generate unused PUT update actions

- app/controllers/application_controller.rb
- app/models/concerns/project_lifecycle.rb
- app/models/concerns/state_machine.rb
- app/models/concerns/task_lifecycle.rb
> tec: #144 Extract a generic state machine

- spec/factories/user.rb
- spec/requests/api/projects_request_spec.rb
- spec/requests/api/tasks_request_spec.rb
- spec/requests/api/users/activations_request_spec.rb
- spec/requests/api/users/authorizations_request_spec.rb
- spec/requests/api/users/projects_request_spec.rb
- spec/requests/api/users/tasks_request_spec.rb
- spec/requests/api/users_request_spec.rb
> tec: #139 Clean the tests

- docs/api/authentication.md
- docs/api/errors.md
- docs/api/index.md
- docs/index.md
> doc: #141 Start API documentation

- Gemfile
- Gemfile.lock
- app/controllers/api/users/projects_controller.rb
- app/controllers/api/users/tasks_controller.rb
- app/models/project.rb
- app/models/task.rb
- app/views/api/users/projects/index.jbuilder
- app/views/api/users/tasks/index.jbuilder
- client/src/api/http.js
- client/src/api/projects.js
- client/src/api/tasks.js
- client/src/store/modules/projects.js
- client/src/store/modules/tasks.js
- docs/api/projects.md
- docs/api/tasks.md
- spec/requests/api/users/projects_request_spec.rb
- spec/requests/api/users/tasks_request_spec.rb
- spec/support/api/schemas/projects/index.json
- spec/support/api/schemas/tasks/index.json
> tec: #149 Paginate index endpoints

- app/views/api/users/projects/index.jbuilder
- app/views/api/users/tasks/index.jbuilder
- spec/requests/api/users/projects_request_spec.rb
- spec/requests/api/users/tasks_request_spec.rb
> fix: #155 Fix pagination when there is no item

- docs/pull_request_template.md
Closes #161.
- add a pull request template to help people to create PR
- do not add a issue template since issues are used for discussions as well
> doc: #161 Provide a pull request template

- docs/_config.yml
- docs/backend/endpoints_design.md
- docs/backend/index.md
- docs/backend/lifecycle_and_state_machine.md
- docs/backend/writing_tests.md
- docs/frontend.md
- docs/index.md
- docs/pull_request.md
- docs/pull_request_template.md
- docs/release.md
- docs/tests.md
Closes #160.
- provide a better technical documentation
> doc: #160 Improve technical documentation

- .travis.yml
- docs/pull_request.md
> tec: Fix Pronto

- client/src/locales/en.js
> imp: Tweak English locale

- client/src/components/tasks/TaskItem.vue
- Fix performances by removing some tooltips
> tec: Try to improve frontend performances

- Dockerfile.dev
- Dockerfile.prod
> tec: Fix instructions order in Dockerfiles

- client/src/components/projects/ProjectCreateForm.vue
- client/src/locales/en.js
Closes #198
- Add a tip for project names at creation
- Homogenize with tip at edition 
> imp: #198 Add a tip for project names

- README.md
- docs/pull_request_template.md
Closes #200 
- Remove note below the screenshot in the README 
- Adapt a bit the PR template
> doc: #200 remove note below screenshot (README)

- client/src/components/Ly/LyIcon.vue
- client/src/components/Ly/LyList/LyList.vue
- client/src/components/Ly/LyList/LyListGroup.vue
- client/src/components/Ly/LyList/LyListItem.vue
- client/src/components/Ly/LyList/index.js
- client/src/components/design/DesignComponentsPage.vue
- client/src/components/projects/ProjectsInboxPage.vue
- client/src/components/tasks/TaskList.vue
- client/src/locales/en.js
- client/src/main.js
- client/src/store/modules/projects.js
- client/src/utils.js
- Fix icon alignment (again :/)
- Provide a ly-list-group component
- Group projects by first character in inbox
> imp: Group projects by first character in inbox

- .travis.yml
- Makefile
- client/.babelrc
- client/package-lock.json
- client/package.json
- client/spec/components/Ly/LyBadge.spec.js
- client/spec/components/Ly/LyButton.spec.js
- client/spec/components/Ly/LyCard.spec.js
- docs/backend/writing_tests.md
- docs/frontend/index.md
- docs/frontend/writing_tests.md
- docs/index.md
- docs/tests.md
Closes #204
- Provide basic front tests
- Configure Travis to execute front tests
- Documentation
> tec: #204 add simple tests to frontend

- client/src/components/Ly/LyPopover/LyPopover.vue
> fix: Fix popover style in production build

- client/src/components/projects/ProjectTimeline.vue
- client/src/locales/en.js
- client/src/locales/fr.js
Related to #171
Rework of and closes #221 
- Make some improvements to English locale file
- Provide a French locale file
Note it does not enable user to change language yet and English is still used for the moment
> i18n: #171 Provide french locale

- CHANGELOG.md
- app/controllers/api/tasks_controller.rb
- client/src/api/tasks.js
- client/src/components/Ly/LyForm/LyFormSelect.vue
- client/src/components/Ly/LyForm/index.js
- client/src/components/Ly/LyModal.vue
- client/src/components/design/DesignComponentsPage.vue
- client/src/components/tasks/TaskAttachProjectForm.vue
- client/src/components/tasks/TaskItem.vue
- client/src/locales/en.js
- client/src/locales/fr.js
- client/src/main.js
- client/src/store/modules/projects.js
- client/src/store/modules/tasks.js
- client/src/styles/app.scss
- client/src/styles/components/_vue_tooltip.scss
- client/src/utils.js
- docs/api/tasks.md
- docs/pull_request_template.md
- spec/requests/api/tasks_request_spec.rb
Closes #214 
- Provide `ly-modal` component
- Provide `ly-form-select` component
- Enable attachment of existing tasks to projects via a modal
> add: #214 Attach existing tasks to project

- docs/pull_request.md
- docs/release.md
- add i18n as a possible commit type
- add a note about GitHub releases
> doc: Improve release process

- CHANGELOG.md
> release: Version Aquarius

- CHANGELOG.md
- app/views/api/tasks/_task.jbuilder
- client/src/components/projects/ProjectCard.vue
- client/src/components/projects/ProjectItem.vue
- client/src/components/projects/ProjectItemFinished.vue
- client/src/components/projects/ProjectsInboxPage.vue
- client/src/components/tasks/TaskItem.vue
- client/src/locales/en.js
- client/src/locales/fr.js
- client/src/store/modules/projects.js
- client/src/store/modules/tasks.js
- docs/api/tasks.md
- spec/support/api/schemas/tasks/task.json
Closes #220
- Improve sync between task and project (use computed data instead of calculation inside getters)
- Homogeneize wording and state checking
- Remove project attributes on task relation
> fix: #220 Improve sync between task and project

- docs/backend/endpoints_design.md
Closes #251 
(I didn't find a good solution yet to merge PRs that need to be rebased on master so I open new PRs so the CI pass :))
> doc: Update endpoint_design

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- client/src/components/design/DesignIndexPage.vue
- client/src/components/design/DesignVisualsPage.vue
- client/src/components/design/DesignWordingPage.vue
- client/src/components/general/HomeLayout.vue
- client/src/locales/en.js
- client/src/locales/fr.js
- docs/api/index.md
- docs/development_environment.md
- docs/frontend/writing_tests.md
- docs/index.md
- docs/production_environment.md
- docs/pull_request.md
- docs/pull_request_template.md
- docs/release.md
- docs/tests.md
Closes #246
- Update links to lessy-community repo
> doc: #246 Update links to lessy-community repo

- app/controllers/api/users/projects_controller.rb
- app/controllers/api/users/tasks_controller.rb
Related to #261 (since I'm not sure it fixes the bug, keep the issue opened)
- Force order on paginated endpoints
> fix: #261 Force order on paginated endpoints

- client/src/components/Ly/LyButton.vue
- client/src/components/design/DesignComponentsPage.vue
- client/src/styles/_forms.scss
Closes #260 
- Force colors to prevent system overrides
- Remove duplicate city on /design/components
>  fix: #260 Force colors to prevent system overrides

- docs/production_environment.md
Related to #263 
- Add a note about `rails db:schema:load` for production
> doc: #263 Document db schema load for production

- client/src/components/users/UserActivateForm.vue
- client/src/locales/en.js
- client/src/locales/fr.js
Related to #263
- Display user errors on activation form
> tec: #263 Display user errors on activation form

- CHANGELOG.md
- app/views/api/projects/_project.jbuilder
- client/src/components/projects/ProjectsInboxPage.vue
- client/src/store/modules/projects.js
- docs/api/projects.md
- docs/backend/endpoints_design.md
- spec/requests/api/users/projects_request_spec.rb
- spec/support/api/schemas/projects/project.json
- Fix ProjectsInbox key
- Remove project.isInProgress from API
> tec: Misc improvements

- client/src/components/projects/ProjectStartForm.vue
Closes #130 
- Change the default duration for a project from 1 month to 2 weeks
> imp: #130 Set default duration for project to 2 weeks

- Gemfile
- Gemfile.lock
- config/cable.yml
> fix: Add Redis gem

- CHANGELOG.md
- docs/production_environment.md
> doc: Fix Nginx documentation for /cable endpoint

- CONTRIBUTING.md
- README.md
Closes #245 
- Add a link to Framateam in README and CONTRIBUTING
> doc: #245 Add link to Framateam

- CHANGELOG.md
Closes https://github.com/lessy-community/lessy/projects/5 (iteration Aquila)
> release: Version Aquila

- README.md
- docs/pull_request.md
- docs/release.md
Closes #288 
- Explain milestones and "Current work" board
> doc: #288 Document new development process

- Dockerfile
- Change current directory at the end of Dockerfile
> tec: Adapt Dockerfile for SquareScale

- .travis.yml
- Change current directory at the end of travis.yml
> tec: Adapt travis.yml for SquareScale

- Dockerfile
This reverts commit 7c3a61309f81eb3bcd17f594333ba593a5924029.
> fix: Revert Dockerfile change for SquareScale

- Gemfile
- Gemfile.lock
- app/lib/flipper_migration.rb
- app/models/user.rb
- config/initializers/flipper.rb
- db/migrate/20180205083244_create_flipper_tables.rb
- db/schema.rb
- docs/feature_flags.md
- docs/index.md
Closes #287 
- Add Flipper gem
- Configure Flipper with ActiveRecord 
- Provide documentation about feature flags
- Provide helpers to add a flag
> tec: #287 Add support for feature flags

- .hound.yml
- .rubocop.yml
- CHANGELOG.md
- app/controllers/api/users_controller.rb
- app/controllers/api/welcome_controller.rb
- app/errors/api_errors.rb
- app/lib/flipper_migration.rb
- app/models/flipper_feature.rb
- app/models/flipper_gate.rb
- app/views/api/welcome/index.jbuilder
- client/.eslintrc.js
- client/src/api/root.js
- client/src/components/general/HomeLayout.vue
- client/src/locales/en.js
- client/src/locales/fr.js
- client/src/store/index.js
- client/src/store/modules/global.js
- config/routes.rb
- db/migrate/20180617164753_create_feature_registration_feature_flag.rb
- db/schema.rb
- db/seeds.rb
- docker-compose-dev.yml
- docs/api/index.md
- docs/api/root.md
- docs/api/users.md
- docs/feature_flags.md
- docs/production_environment.md
- spec/requests/api/users_request_spec.rb
- spec/requests/api/welcome_request_spec.rb
- spec/support/api/schemas/welcome/index.json
Closes #303 
- tec: Restart docker containers when appropriate 
- tec: Improve `FlipperMigration.create_flag` method
- doc: Add naming convention for feature flags
- create a new feature flag `feature_registration` to block registrations if disabled
> add: #303 Allow administrator to disable registration

- .travis.yml
- CONTRIBUTING.md
- CONTRIBUTORS.md
- README.md
- client/src/components/design/DesignVisualsPage.vue
- docs/backend/index.md
- docs/production_environment.md
Corresponds to https://github.com/lessy-community/lessy/pull/302 but rebased on master and with better commit message.
- Fix miscellaneous typos
> doc: Fix miscellaneous typos

- docs/production_environment.md
- Document production with image from hub
- Update information to setup first user
> doc: Update production documentation

- CHANGELOG.md
> release: Version Aries

- app/controllers/api/users/authorizations_controller.rb
- app/controllers/api/users/password_resets_controller.rb
- app/controllers/api/users/passwords_controller.rb
- app/controllers/api/users_controller.rb
- app/controllers/api/welcome_controller.rb
- app/controllers/api_controller.rb
- Refactor `render_errors` with `render_error` when there is only one error
> tec: Refactor render_errors with render_error

- client/src/components/Ly/LyPopover/LyPopoverItem.vue
- client/src/router.js
- client/src/store/modules/users.js
- tec: Reorganize routes in router.js
- tec: Remove useless info in user findById getter
- tec: Accept "to" prop in LyPopoverItem 
> tec: Various tech commits

- client/src/components/App/AppHeader.vue
- client/src/components/App/AppHeaderLink.vue
- client/src/components/dashboard/DashboardPage.vue
- client/src/components/general/LoadingPage.vue
- client/src/components/general/NotFoundPage.vue
- client/src/components/layouts/LayoutApplication.vue
- client/src/components/layouts/LayoutApplicationHeader.vue
- client/src/components/layouts/LayoutDefault.vue
- client/src/components/layouts/LayoutEmpty.vue
- client/src/components/layouts/LayoutSingleForm.vue
- client/src/components/projects/ProjectsHeader.vue
- client/src/components/tasks/TasksHeader.vue
- client/src/locales/en.js
- client/src/locales/fr.js
- Rewrite AppHeader to be reusable
- Migrate all headers to AppHeader
> tec: Refactor AppHeader

- CHANGELOG.md
- app/controllers/api/users/activations_controller.rb
- app/controllers/api/users/authorizations_controller.rb
- app/controllers/api/users/passwords_controller.rb
- app/controllers/api/users_controller.rb
- app/controllers/api_controller.rb
- app/errors/api_errors.rb
- app/lib/json_web_token.rb
- app/models/user.rb
- client/src/components/mixins/ResourcesLoader.js
- client/src/components/profile/ProfileIdentityEditForm.vue
- client/src/components/profile/ProfilePage.vue
- client/src/locales/en.js
- client/src/locales/fr.js
- docs/api/authorizations.md
- docs/api/index.md
- docs/api/users.md
- docs/api/websocket.md
- spec/json_web_token_spec.rb
- spec/requests/api/projects_request_spec.rb
- spec/requests/api/tasks_request_spec.rb
- spec/requests/api/users/authorizations_request_spec.rb
- spec/requests/api/users/projects_request_spec.rb
- spec/requests/api/users/tasks_request_spec.rb
- spec/requests/api/users_request_spec.rb
- Clean authorizations_request_spec file
- Refactor auth token related-methods
- Rename Authentication into Authorization
- Refactor render_error in api_controller
- Change ProfileEditForm in ProfileIdentityEditForm
- Log out client only if error is unauthorized 
> tec: Various technical commits

- .rubocop.yml
- app/controllers/api/users/authorizations_controller.rb
- app/controllers/api/users/passwords_controller.rb
- app/controllers/api_controller.rb
- app/errors/api_errors.rb
- app/models/user.rb
- app/views/api/users/passwords/create.jbuilder
- client/src/api/http.js
- client/src/api/terms_of_services.js
- client/src/api/users.js
- client/src/auth.js
- client/src/components/general/SudoModal.vue
- client/src/components/profile/ProfilePage.vue
- client/src/components/profile/ProfilePasswordNewForm.vue
- client/src/locales/en.js
- client/src/locales/fr.js
- client/src/store/modules/users.js
- docs/api/authorizations.md
- docs/api/users.md
- spec/requests/api/users/authorizations_request_spec.rb
- spec/requests/api/users/passwords_request_spec.rb
- spec/support/api/schemas/users/passwords/create.json
Related to #43 
- Add a sudo mode for critical actions
- Add a password edition form
> add: #43 Add support for password edition

- CHANGELOG.md
- app/controllers/api/users_controller.rb
- client/src/api/http.js
- client/src/api/users.js
- client/src/components/profile/ProfileDeleteAccount.vue
- client/src/components/profile/ProfilePage.vue
- client/src/locales/en.js
- client/src/locales/fr.js
- client/src/store/modules/users.js
- config/routes.rb
- docs/api/users.md
- spec/requests/api/users_request_spec.rb
Related to #43 
- Add account deletion feature
> add: #43 Add account deletion feature

- CHANGELOG.md
- app/controllers/api/users_controller.rb
- app/views/api/users/update.jbuilder
- client/src/api/users.js
- client/src/components/profile/ProfileIdentityEditForm.vue
- client/src/components/profile/ProfilePage.vue
- client/src/locales/en.js
- client/src/locales/fr.js
- client/src/store/modules/users.js
- config/routes.rb
- docs/api/users.md
- spec/requests/api/users_request_spec.rb
- spec/support/api/schemas/users/update.json
Closes #43
- Add identity edition
> add: #43 Add identity edition

- client/src/components/tasks/TaskCreateForm.vue
- client/src/locales/en.js
- client/src/locales/fr.js
Closes #226 
- Show successful info on task creation
> imp: #226 Show successful info on task creation

- client/src/components/profile/ProfileLanguageForm.vue
- client/src/components/profile/ProfilePage.vue
- client/src/locales/en.js
- client/src/locales/fr.js
- client/src/locales/index.js
- client/src/router.js
Closes #171 
- Add support to change the language
> add: #171 Add support for french

- CHANGELOG.md
> release: Version Ara

- client/src/components/App/AppMenuLink.vue
- client/src/components/layouts/LayoutProfile.vue
- client/src/store/modules/tasks.js
- Restore exact active AppMenuLink
- Revert changes in tasks counters
> fix: Various fixes

- client/src/components/tasks/TaskCreateForm.vue
- client/src/components/tasks/TaskIndicators.vue
- client/src/components/tasks/TaskItem.vue
- client/src/components/tasks/TaskPlanModal.vue
- client/src/components/tasks/TaskSelectList.vue
- client/src/components/tasks/TaskSelectableItem.vue
- client/src/components/tasks/TasksPlanner.vue
- client/src/components/today/TodayPage.vue
- client/src/locales/en/messages.js
- client/src/locales/fr/messages.js
- client/src/store/modules/tasks.js
Related to #175 
- Plan task through a modal
- Setup a new workflow for planning
- Separate list of finished and unfinished tasks on today page
- Remove possibility to plan from backlog or project pages
> add: #175 Improve today planning feature

- client/src/components/tasks/TasksCompleteDayModal.vue
- client/src/components/tasks/TasksPlanner.vue
- client/src/components/today/TodayPage.vue
- client/src/locales/en/messages.js
- client/src/locales/fr/messages.js
Related to #175
- Add a "complete your day" feature
> add: #175 Add the "finish your day" feature

- client/src/components/projects/ProjectShowPage.vue
- client/src/components/tasks/TaskList.vue
- client/src/locales/en/messages.js
- client/src/locales/fr/messages.js
- client/src/store/modules/tasks.js
Closes #292 
- Separate unfinished tasks in project
> imp: #292 Separate unfinished tasks in project

- client/src/components/projects/ProjectsInboxPage.vue
- client/src/locales/en/messages.js
- client/src/locales/fr/messages.js
Closes #294 
- List projects in progress in inbox
> imp: #294 List projects in progress in inbox

- app/mailers/user_mailer.rb
- client/src/locales/en/messages.js
- spec/mailers/user_mailer_spec.rb
Related and closes #349 
Improve some of the English language used throughout the application.
> i18n: Improve the English messages

- CHANGELOG.md
- app/controllers/api/projects_controller.rb
- app/models/project.rb
- client/src/api/projects.js
- client/src/components/projects/ProjectDeleteModal.vue
- client/src/components/projects/ProjectShowPage.vue
- client/src/locales/en/messages.js
- client/src/locales/fr/messages.js
- client/src/store/modules/projects.js
- client/src/store/modules/tasks.js
- config/routes.rb
- docs/api/projects.md
- spec/requests/api/projects_request_spec.rb
Closes #350 
- Add a button to delete a project
> add: #350 Delete a project

- Dockerfile
Fix Dockerfile. Bug introduced in ecd11be6cf88daf0adff7be6ee18208e0279b24a
> fix: Fix production Dockerfile

- client/src/components/Ly/LyModal.vue
- client/src/components/design/DesignComponentsPage.vue
- client/src/components/general/SudoModal.vue
- client/src/components/general/TermsOfServiceModal.vue
- client/src/components/projects/ProjectDeleteModal.vue
- client/src/components/projects/ProjectEditDueDateModal.vue
- client/src/components/projects/ProjectFinishModal.vue
- client/src/components/projects/ProjectStartModal.vue
- client/src/components/projects/ProjectsStartNewModal.vue
- client/src/components/tasks/TaskAttachProjectModal.vue
- client/src/components/tasks/TaskConfirmAbandonModal.vue
- client/src/components/tasks/TaskTransformInProjectModal.vue
- client/src/components/tasks/TasksCompleteDayModal.vue
- client/src/components/tasks/TasksPlanModal.vue
- Add a cross to close modals
- Support `escape` to close modals 
> imp: Add native closing for modals (esc and button)

- Procfile
> tec: Remove Rails pid file at starting

- client/src/components/dashboard/DashboardPage.vue
- client/src/components/tasks/TasksChart.vue
- Force min-height on tasks chart bars
- Show project badges on tasks 
> imp: Improve tasks chart

- CHANGELOG.md
- app/controllers/api/users/tasks_controller.rb
- client/src/api/tasks.js
- client/src/components/Ly/LyForm/LyFormGroup.vue
- client/src/components/tasks/TaskCreateForm.vue
- client/src/components/tasks/TasksBacklogPage.vue
- client/src/components/tasks/TasksCompleteDay.vue
- client/src/components/tasks/TasksPlanModal.vue
- client/src/components/tasks/TasksPlanner.vue
- client/src/components/today/TodayPage.vue
- client/src/locales/en/messages.js
- client/src/locales/fr/messages.js
- client/src/store/modules/tasks.js
- docs/api/tasks.md
- spec/requests/api/users/tasks_request_spec.rb
- Move the "end of day" button
- Move TasksCompleteDay modal in page 
- Add task list and form in the CompleteDay section
> imp: Improve "end of day" feature

- client/src/components/today/TodayPage.vue
- client/src/locales/en/messages.js
- client/src/locales/fr/messages.js
Closes #
- Fix completed mode on today page
- i18n: Change wording when user finished no tasks 
> imp: Complete day

- client/src/components/tasks/TasksPlanModal.vue
- Close plan modal when creating tasks (bug introduced in 44003af2a6f9bf0f2f2adab632ff948b9902615d)
> fix: Close plan modal when creating tasks

- client/src/components/projects/ProjectsPage.vue
- client/src/components/tasks/TasksPage.vue
- client/src/locales/en/messages.js
- client/src/locales/fr/messages.js
- client/src/router.js
Closes #256 
- Remove backlog and inbox notions
- Default routes are now `/projects` and `/tasks` (old ones still exist to assure backward compatibility)
> imp: Remove backlog and inbox notions

- README.md
> doc: #225 Update wording of to use "recover" term

- client/src/components/App/AppMenuLink.vue
Closes #227
- Don't change opacity of links
- Add a background on hover and active
> imp: #227 Improve app-menu links readability

- app/dashboards/user_dashboard.rb
- Show user creation date in admin
> imp: Show user creation date in admin

- CHANGELOG.md
- config/environments/production.rb
- config/secrets.yml
- docs/production_environment.md
Closes #57
- Add new environment variables to configure SMTP servers
> tec: #57 Improve support of SMTP servers

- client/src/components/App/AppHeader.vue
- client/src/components/App/AppPage.vue
- client/src/components/Ly/LyButton.vue
- client/src/components/Ly/LyForm/LyFormSelect.vue
- client/src/components/general/HomePage.vue
- client/src/components/layouts/LayoutEmpty.vue
- client/src/components/onboarding/OnboardingPage.vue
- client/src/components/profile/ProfileLanguageForm.vue
- client/src/components/profile/ProfilePage.vue
- client/src/components/projects/ProjectCard.vue
- client/src/components/projects/ProjectCreateForm.vue
- client/src/components/projects/ProjectsPage.vue
- client/src/components/projects/ProjectsStartNewForm.vue
- client/src/components/tasks/TaskTransformInProjectModal.vue
- client/src/locales/en/messages.js
- client/src/locales/fr/messages.js
- client/src/router.js
Closes #178 
- Improve basic UX of LyFormSelect
- Provide an onboarding page
- Add a language form on home and onboarding
> add/: #178 Provide onboarding
