lessy-community/lessy

app/controllers/api/projects_controller.rb, app/models/project.rb, app/views/api/projects/_project.jbuilder, app/views/api/projects/start.jbuilder, client/src/api/projects.js, client/src/components/forms/EditProject.vue, client/src/components/forms/StartProject.vue, client/src/components/layout/AppHeader.vue, client/src/components/pages/Dashboard.vue, client/src/components/pages/projects/Show.vue, client/src/components/pages/projects/Start.vue, client/src/router.js, client/src/store/modules/projects.js, client/src/utils.js, config/initializers/json_param_key_transform.rb, config/routes.rb, db/migrate/20170115112412_add_dates_to_project.rb, db/schema.rb, spec/factories/projects.rb, spec/models/project_spec.rb, spec/requests/api/projects_request_spec.rb, spec/requests/api/users_request_spec.rb, spec/support/api/schemas/projects/project.json
Fix #5
tech considerations: dates should be stored in UTC
=> add: #5 Start projects

app/controllers/api/tasks_controller.rb, client/src/api/tasks.js, client/src/components/tasks/TaskItem.vue, client/src/locales/en.js, client/src/store/modules/tasks.js, spec/requests/api/tasks_request_spec.rb
Since pending tasks go directly in the backlog, there is no need of this
buggy feature.
Fix #120
=> fix: #120 Revert #113 (send to backlog feature)

client/src/components/Ly/LyCard.vue
- Remove `background-image` if no `image` attribute is given to card
=> tec: Remove back url on cards with no illustration

CHANGELOG.md, app/controllers/api/users/tasks_controller.rb, app/models/concerns/project_lifecycle.rb, app/models/concerns/task_lifecycle.rb, app/views/api/projects/_project.jbuilder, app/views/api/tasks/_task.jbuilder, client/src/api/projects.js, client/src/components/projects/ProjectFinishForm.vue, client/src/components/projects/ProjectTimeline.vue, client/src/components/projects/ProjectsInboxPage.vue, client/src/components/tasks/TaskItem.vue, client/src/locales/en.js, client/src/store/modules/projects.js, client/src/store/modules/tasks.js, db/migrate/20171224225137_update_task_state_on_not_started_projects.rb, db/schema.rb, docs/api/projects.md, docs/api/tasks.md, docs/backend/endpoints_design.md, spec/models/task_spec.rb, spec/requests/api/projects_request_spec.rb, spec/requests/api/users/tasks_request_spec.rb, spec/support/api/schemas/projects/project.json, spec/support/api/schemas/tasks/task.json
Closes #182 
- make tasks "newed" when created on non-started projects
- make newed tasks "started" when  (re)starting a project
- do not list "newed" tasks in backlog
- show number of tasks attached to projects in inbox
=> add: #182 Do not list tasks in backlog for non running projects

CHANGELOG.md, app/controllers/api/projects_controller.rb, app/controllers/api/users/projects_controller.rb, app/models/project.rb, app/views/api/projects/_project.jbuilder, app/views/api/tasks/_task.jbuilder, client/src/components/projects/ProjectCreateForm.vue, client/src/components/projects/ProjectLayout.vue, client/src/locales/en.js, client/src/router.js, client/src/store/modules/projects.js, client/src/store/modules/tasks.js, db/migrate/20171226101352_add_slug_to_project.rb, db/schema.rb, db/seeds.rb, docs/api/projects.md, docs/api/tasks.md, spec/factories/projects.rb, spec/models/project_spec.rb, spec/requests/api/projects_request_spec.rb, spec/requests/api/users/projects_request_spec.rb, spec/support/api/schemas/projects/project.json, spec/support/api/schemas/tasks/task.json
Closes #168 
- Provide a `slug` attribute to Project
- Remove project name's constraints
- Infer slug from project name
=> imp: #168 Relax requirements for project names

client/src/components/Ly/LyList/LyListGroup.vue, client/src/store/modules/projects.js
- Group projects per slug's first character
- Fix group header to `2rem`
=> imp: Improve ordering of project list

client/src/components/projects/ProjectEditForm.vue, client/src/locales/en.js
- Remove project name constraints on edition
=> fix: Enable project name full edition

client/src/components/Ly/LyPopover/LyPopover.vue, client/src/components/Ly/LyPopover/LyPopoverSeparator.vue, client/src/components/Ly/LyPopover/index.js, client/src/components/design/DesignComponentsPage.vue, client/src/components/projects/ProjectCreateForm.vue, client/src/components/projects/ProjectLayout.vue, client/src/components/projects/ProjectsInboxPage.vue, client/src/components/tasks/TaskAttachProjectModal.vue, client/src/components/tasks/TaskItem.vue, client/src/components/tasks/TaskTransformInProjectModal.vue, client/src/locales/en.js, client/src/locales/fr.js, client/src/main.js, client/src/router.js, client/src/styles/components/_vue_tooltip.scss
Closes #179 
- Fix tooltip CSS
- Provide a `ly-popover-separator` component
- Make transformation of task in project possible via a modal
- Extract modals from `task-item`
=> add: #179 Enable transformation of task in project

client/src/components/Ly/LyModal.vue, client/src/components/tasks/TaskConfirmAbandonModal.vue, client/src/components/tasks/TaskItem.vue, client/src/locales/en.js, client/src/locales/fr.js, client/src/styles/app.scss
Closes #234 
- Handle task abandon through a modal
- Refactor modal selection in task-item
- Improve modal rendering when opened
=> imp: #234 Handle task abandon confirmation through modal

client/src/components/projects/ProjectsInboxPage.vue, client/src/components/tasks/TaskAttachProjectForm.vue, client/src/store/modules/projects.js
Closes #243 
- Rename `notStarted` projects in `future` projects
- Adapt related condition so finished projects are not listed as future projects 
=> fix: #243 Remove finished projects of future list

.travis.yml, CHANGELOG.md
- Remove test suite for Ruby 2.3 (we only support Ruby 2.4 officialy)
=> tec: Remove test suite for Ruby 2.3

CHANGELOG.md, app/controllers/api/tasks_controller.rb, app/controllers/api/users/tasks_controller.rb, app/models/task.rb, docs/api/tasks.md, spec/models/task_spec.rb, spec/requests/api/tasks_request_spec.rb
Closes #267 
- Sync task's state on project id change
- Refactor with syncing on task creation
- Document the API change
=> fix: #267 Sync task's state on project change

Dockerfile, Dockerfile.dev
Closes https://github.com/lessy-community/lessy/issues/305
`openssl-dev` seems to not be needed anymore and was conflicting with
`libressl-dev` (dependency of `postgresql-dev`).
npm@5 was failing with `Error: write after end` error. It has been fixed
in npm@6 so we just upgrade.
=> fix: #305 Fix Docker build

Gemfile, Gemfile.lock, app/controllers/api/users/tasks_controller.rb, app/models/task.rb, spec/models/task_spec.rb
Closes #301 
- Provide with_advisory_lock gem 
- Make explicit the task order setting 
- Put sync_order and save within a lock
=> fix: #301 Fix race condition when setting task order

client/src/components/general/LoadingPage.vue, client/src/locales/en.js, client/src/locales/fr.js
Sometimes, the loading page is stuck because we weren't able to handle
correctly an error. It might happen after an upgrade of Lessy and the
only known solution is to re-login.
This commit adds a "reset" button to the loading page, and it appears
after 10 seconds of loading.
=> fix: Add workaround for resource loading failures

CHANGELOG.md, app/models/user.rb, spec/models/user_spec.rb, spec/requests/api/users_request_spec.rb
Closes #337
- Handle old tokens that didn't have `data` payload
- Handle retrieving deleted user
=> fix: #337 Fix invalid auth token parsing

.travis.yml, Dockerfile, Dockerfile.dev
Related to and close #352
Dockerfile doesn't build without nodejs-npm package since `nodejs` no
longer comes with `npm` in Alpine 3.6.
=> tec: Update Dockerfiles

.rubocop.yml, CHANGELOG.md, app/models/concerns/task_lifecycle.rb, client/src/api/tasks.js, client/src/components/tasks/TaskItem.vue, client/src/components/tasks/TasksPlanner.vue, client/src/locales/en/messages.js, client/src/locales/fr/messages.js, client/src/store/modules/tasks.js, docs/api/tasks.md, spec/factories/tasks.rb, spec/models/task_spec.rb
- Provide a "unplan" button on tasks planned for today
=> add: Unplan task

client/src/components/Ly/LySection.vue, client/src/components/design/DesignComponentsPage.vue, client/src/components/projects/ProjectShowPage.vue, client/src/components/projects/ProjectsPage.vue
- Provide an actions slot for sections 
- Center the projects creation button and form 
- Remove the plus icon on project creation button
- Use ProjectCardDeck component on projects page
- Move actions of ProjectShow in section slot
=> imp: Improve projects pages

client/src/components/profile/ProfilePage.vue
- Hide the timezone form if user is inactive
=> fix: Hide the timezone form if user is inactive
